---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-certificates
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: "${SECRET_CLUSTER_LOCAL_DOMAIN/./-}"
          namespace: default
        spec:
          secretName: "${SECRET_CLUSTER_LOCAL_DOMAIN/./-}-tls"
          issuerRef:
            name: letsencrypt-staging
            kind: ClusterIssuer
          commonName: "${SECRET_CLUSTER_LOCAL_DOMAIN}"
          dnsNames:
            - "${SECRET_CLUSTER_LOCAL_DOMAIN}"
            - "*.${SECRET_CLUSTER_LOCAL_DOMAIN}"