---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: letsencrypt-production
        spec:
          acme:
            server: https://acme-staging-v02.api.letsencrypt.org/directory
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            privateKeySecretRef:
              name: letsencrypt-production
            solvers:
              - dns01:
                  cloudflare:
                    email: "${SECRET_CLOUDFLARE_EMAIL}"
                    apiTokenSecretRef:
                      name: cloudflare-api-token-secret
                      key:  api-token
                selector:
                  dnsZones:
                    - ${SECRET_DOMAIN}