apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7MrFo/XZ3Ktzi+PSGxxAxLGlC2W7VfSadht7n8hzxz8eFhT5XExefw==,iv:nmJpfmaNSW5bdM533Bo29Z3L9MtT4NPFUbK7cyq8S3Y=,tag:C6iMnjJeqlAmlAW+KQ30eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbE50bEN0ZWtLVFBQajZn
            ZVdDRWNJdDEzRVdNQWlZTlJNTERkS21LOUM4Ckd2alJ5Q2tvejBmL2Z6TGU5OWlX
            T2FMS255TVlMaHV2MDFueFk0cnI2ZVEKLS0tIDYzWmx4d1IxTytpOUFBRjNOaFNR
            eFBTMzEvclBldTIzaXlaY3NZWVNvYUUK/Q6EAux4Sd3GCqwdOSiSYd5XZ2fAdRg8
            VrilTSBt+RiOCkPRQhfXkaWhIdXjaghu31bb+yEGZfw3FHFoa1ZZSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-15T18:41:26Z"
    mac: ENC[AES256_GCM,data:7hPZA2eMU4QL1WDamGm72hYEtx4mbIYrRT+2q0JKHoNtwnxwCBO9qPLHHj5bqRLwx2e8TbvcJKp1R3UV0FnQuHEzX8IgSMKj/ugAKSV41NNWZvRMo67OadjVjrgf8cjZFeoDKuis9bPOay2BJcTiZ/+vcdLNdV8RIYa4xJmhenw=,iv:Y5P/Mii0ztyuH8qBC8Ju6xmT7YClOOVOoKdOq3egxpk=,tag:DptWxeTtsmyM18XKMESZYA==,type:str]
    pgp: []
    encrypted_regex: ^(data||stringData)$
    version: 3.7.3
