apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:oKeTyBeiHSo5BeJA19KFg+JIbk8JUYH9gjMRrHQIGh8fCp2dXWC2zQ==,iv:vhhTNdYpX2EVFvx10gwTKNofhi0HhN+u7haQqpal3J8=,tag:wyqC+c8OsAe4ML+hkOy+vA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWUVFSk5ObXF4ZytsSEdL
            SGxiZ0VCTWJCSzBOV3VscjVwd3h1RzdvTmtNCjMzVng5eThIYS9HR1hoODloS2NG
            aEZSTzNOSmswT2NNaVNQczJzdXM5c0EKLS0tIDdTdWdzN1NlVGNJZ0ZsQ1lPanhl
            TDNoV25Yd1ZhUmNpMnJhUmphaVpNdnMK5nnK7bS2Ix7CGC0MShwzc0O+FZB7oG3P
            nv1mRYXKcC1EyVIZ46u6USY59UUUD7hG5FV1lgiCenXAZoeHmRyXug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-19T15:39:50Z"
    mac: ENC[AES256_GCM,data:d+q763CmQfIu1elo9MI4tUJpO2YGu9x+1UdE1htz1Wiie43tCdiJeP4NfMbJ/85hlZbAVXFMopfPj2eypLBWu7+PkxmmHNvvIoJ2hDCHUNhMIP/shoVYRXt+9FPsg21F+k06MI+6SFxHIzbY1gSkya3zp6F4ER6HqGwNtkY2c6M=,iv:YTM1zxsPqecfwLppG3F7KxxPmyelbP1nvu9fEBv5yQI=,tag:yxhmWfSeXqenViSeZYTgNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
