---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - jetstack-charts.yaml
  - metallb-charts.yaml
  - dysnix-charts.yaml
  - traefik-charts.yaml
  - longhorn-charts.yaml
  - prometheus-community-official.yaml
  - grafana-charts.yaml