---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      version: 20.2.1
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    deployment:
      replicas: 1
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--log.level=DEBUG"
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    rbac:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: 192.168.86.50 # this should be an IP in the MetalLB range
    persistence:
      enabled: true
      name: data