apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:cyPXkSc6p/M=,iv:oJfZr7E65sn8815evo+10VOunulO1FGLUXDq0Rdfy3g=,tag:8dWh0DRpkdrLlQfZkw2tmg==,type:str]
    admin-user: ENC[AES256_GCM,data:eDmaStUCyLo=,iv:tUYQa2WwfbtB0Tn2jITUTQluo55ujhK4rhX5aIoIYWk=,tag:PZiiuHSGqsf0cxdg6C/uBw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-admin-credentials
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Unc4Z0phUFNTQnVyVXEw
            MWQ4TGFCaStEbC8vQkRTaTNWQjNkT2pIcVVjCms2Qm9mSzFMSTdkS2dpbnZRd3do
            eXZ4c2xLUE1abWNPQWlrY1BnNzlrbGcKLS0tIDAxcDdKQWdRMlJVS1dFdU9QYkdI
            L3BoM0JXVzk5T09NaHVUdGZRckdPS2MKER2pZu0XpDAevp1vutWOarsSLuAMH2dJ
            +nqD7U6jhAiaDs8U2uNU7PfXgfpp1zo70V4g1phmydbS1bYH3Td5Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-18T13:42:18Z"
    mac: ENC[AES256_GCM,data:Z/79XYRYB6zwmf2w5yCstqDTLnW2RiPO2oYK2OUYs4jbW+Ge16+KgOQmUt3u1slLkO5zVEHUvZnwaeEtYHpNsObdRGwz5Fd2mcFLSwBUOpQoN30WHDwebJDRrpo4GF/sEMQh4/w966uhBWsHWuRPLVCR/hxxV04IEM6kIy01OSM=,iv:Rco8oKygKnJlccdB25OknF349RMKiSp77wVnptywF3g=,tag:QOr4/mG9Ubv3MkMNlpzrRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data||stringData)$
    version: 3.7.3
