---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  interval: 1m0s
  values:
    global:
      namespaceOverride: metallb-system
    controller:
      logLevel: debug
    prometheus:
      serviceAccount: kube-prometheus-stack-prometheus
      namespace: monitoring
      podMonitor:
        enabled: false
      prometheusRule:
        enabled: false
    speaker:
      tolerateMaster: true
      logLevel: info
      frr:
        enabled: false
        image:
          repository: docker.io/frrouting/frr
          tag: v7.5.1
    crds:
      enabled: true
        
