---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.3.2
  values:
    longhornManager:
      nodeSelector:
        disktype: "ssd"
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
    longhornUI:
      nodeSelector:
        disktype: "ssd"
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
    defaultSettings:
      systemManagedComponentsNodeSelector: "disktype:ssd"
      taintToleration: "CriticalAddonsOnly=true:NoExecute"
      backupTarget: s3://longhorn-backup@eu-north-se1/
      backupTargetCredentialSecret: longhorn-truenas-s3-backup-credentials
    