apiVersion: v1
kind: Secret
metadata:
    name: longhorn-truenas-s3-backup-credentials
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kcGhtfY=,iv:wKy/QSb2XZgkSDgiO4V3SrfAZqoVNefvD6Lw3QXabj8=,tag:R7Q+fEzXBTzSWvNN26kMRg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ApW2c88uIc0=,iv:irf2aROA09y8MFg8wpv7e/gffd1hn9V7odxDvZd1Tio=,tag:gZhdrDAGj4sVRuAArSbZFA==,type:int]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:SXOvLBad4F/BIU4i51fBv+FYbgTrUAH/,iv:4l/rKSBqnsrk9Q3iIGVKvMs+Dc3q5173pBbtKx1gyuY=,tag:yrZWhCdtrlClA7NqyMHb2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMExNUE9tZ2REenBhbDFU
            dlpYeHlQRWIrYXJHbzNPY1lnUms0RUk2TWhnCmJFSHVzbnY4bERUVHVqb29YWVBy
            RUgxK3psMTM1YitKUk1jOTkyb3lGSGcKLS0tIFkwSDRwWHJkZmFMZm04R3JIVG5N
            dWdQT2lkTFlUQVhkOTh2dCtyeWVlNzAKV4wGmGsy4SNUNZ5qOijT9X4aduD5kz5u
            InPJBuDrtxtc3PFpmYOiXjQ9BQsIuy2XCACIAVNFz7ulXGfvL821FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-29T20:39:37Z"
    mac: ENC[AES256_GCM,data:+zZ1Y3PqM7cLQ3703/QlRiVUhMzXtN5kddgznvS5FFIKNFebdGDQWvV562kntXvzi29e6gjHFwbVb1CCOo7kFry16ii0M+jG0Byb/iF1Ensq8HN3WcfLMulm1i+CMI4VLvXvjFJ4YwpRo7e+Qb5yHAEd4+qFpY2TByve9wKrF3M=,iv:c2Vo4UPrG++HmNp64dZMdYQOletj2Q51T27z0zeKk3g=,tag:5nTEOwGHVQFYe5we45Epxw==,type:str]
    pgp: []
    encrypted_regex: ^(data||stringData)$
    version: 3.7.3
