apiVersion: v1
data:
    AWS_ENDPOINTS: ENC[AES256_GCM,data:RQuM8/T/41t2TK32sLGjvYza2LvqaEaLGG0BFPes3M1bA6Zg,iv:0xCFhwhP0iARzAyCvZ6AoqBFc4PebXQzu7mLpjeC/H4=,tag:cU+rWYWkbCpTcZyV7/rXcA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:JaJTRQ975U4zcVfB,iv:qFP/cgth9kV3ajG9K9XKzG/B/+79/zgYFyEbxrli+zI=,tag:xl+BjEKjxO1YvOr9Ela1qg==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:pMKVWBcMfxE=,iv:VtgZNkViokv22h4iW3B/5HEMehorHOLwnn7B5tWDj+0=,tag:8Rp/gtF3VMZntGsB22Q1ZQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: longhorn-truenas-s3-backup-credentials
    namespace: longhorn-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkZSaXlxNkRvNld0alRC
            RTgxLzVVK01VQnhRYmpYb056TWh3NHlwaUQwCm1TM0RYMU5IdVluN2FQc1NrY2N6
            RUdPcXVOZWZlaWFSV2UzY0plakRuUk0KLS0tIHJHYVRvdGE0aFpFV1BxdkdsSlUr
            WWE4MjNWZXlML3poZG9PbENzVTFSNmcKrcbMVQPjluDlDWmPa7O3oi/idx2jpFly
            d+tprXusN0HJrCdNigWmGtwGQCwEmxLp5P5764xh37OkmwTLKPifZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-30T20:51:03Z"
    mac: ENC[AES256_GCM,data:KGn7E39LD/5k5cO/zbPjWH68cheDq043o40wgiG5VUtES0Zq+O9Ix8PAbuhVAHtwgJ6Or4LlvVFe0p64qMNjhpbgBpSzl1BXglBmutLijcyYxrr1shTSYsPYKvcLMm9UWHN9TCPI1FG07aNktuBY2ujLOt8YkUxK4rE42Bv5uJU=,iv:FDZ3pXjwSs6sLWXfWUVruxQAdB+ZDYRp+MdJu4Bq+Ac=,tag:EZjlnrtpIDCJUgZiymF5Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data||stringData)$
    version: 3.7.3
