apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaimx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn # Empty string must be explicitly set otherwise default StorageClass will be set