---
apiVersion: v1
kind: Namespace
metadata:
  name: home
  labels:
    name: home

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassist-pv-claim3
  namespace: home
  labels:
    app: homeassist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn # Empty string must be explicitly set otherwise default StorageClass will be set
#  volumeName: homeassist-pv2

---
apiVersion: v1
kind: Secret
metadata:
  name: homeassist-config
type: Opaque
data:
  configuration.yaml: aG9tZWFzc2lzdGFudDoKICAjIE5hbWUgb2YgdGhlIGxvY2F0aW9uIHdoZXJlIEhvbWUgQXNzaXN0YW50IGlzIHJ1bm5pbmcKICBuYW1lOiBIb21lCiAgIyBMb2NhdGlvbiByZXF1aXJlZCB0byBjYWxjdWxhdGUgdGhlIHRpbWUgdGhlIHN1biByaXNlcyBhbmQgc2V0cwogIGxhdGl0dWRlOiAwCiAgbG9uZ2l0dWRlOiAwCiAgIyBJbXBhY3RzIHdlYXRoZXIvc3VucmlzZSBkYXRhIChhbHRpdHVkZSBhYm92ZSBzZWEgbGV2ZWwgaW4gbWV0ZXJzKQogIGVsZXZhdGlvbjogMAogICMgbWV0cmljIGZvciBNZXRyaWMsIGltcGVyaWFsIGZvciBJbXBlcmlhbAogIHVuaXRfc3lzdGVtOiBtZXRyaWMKICAjIFBpY2sgeW91cnMgZnJvbSBoZXJlOiBodHRwOi8vZW4ud2lraXBlZGlhLm9yZy93aWtpL0xpc3Rfb2ZfdHpfZGF0YWJhc2VfdGltZV96b25lcwogIHRpbWVfem9uZTogU3dlZGVuL1N0b2NraG9sbQoKICBhdXRoX3Byb3ZpZGVyczoKICAgIC0gdHlwZTogaG9tZWFzc2lzdGFudAoKZGVmYXVsdF9jb25maWc6CgpodHRwOgogIGlwX2Jhbl9lbmFibGVkOiBmYWxzZQogIGxvZ2luX2F0dGVtcHRzX3RocmVzaG9sZDogMTAKICB1c2VfeF9mb3J3YXJkZWRfZm9yOiB0cnVlCiAgdHJ1c3RlZF9wcm94aWVzOgogICAgLSAxMC40My4wLjAvMTYKICAgIC0gMTkyLjE2OC44Ni4wLzI0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassist-deployment
  namespace: home
  labels:
    app: homeassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassist
  template:
    metadata:
      labels:
        app: homeassist
    spec:
      containers:
        - name: homeassist
          image: homeassistant/home-assistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: homeassist-persistent-storage
            - mountPath: "/config/configuration.yaml"
              subPath: "configuration.yaml"
              name: homeassist-config
      volumes:
        - name: homeassist-config
          secret:
            secretName: homeassist-config 
            defaultMode: 0777
        - name: homeassist-persistent-storage
          persistentVolumeClaim:
            claimName: homeassist-pv-claim3
---
apiVersion: v1
kind: Service
metadata:
  name: homeassist
  namespace: home
spec:
  type: ClusterIP
  selector:
    app: homeassist
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8123

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: homeassist-ingress-tcp
#   namespace: ingress
#   annotations:
#     metallb.universe.tf/allow-shared-ip: "homeassist-shared-ip"
# spec:
#   selector:
#     name: nginx-ingress-microk8s
#   type: LoadBalancer
#   # loadBalancerIP is optional. MetalLB will automatically allocate an IP
#   # from its pool if not specified. You can also specify one manually.
#   # loadBalancerIP: x.y.z.a
#   loadBalancerIP: 192.168.1.10
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 80
#     - name: https
#       protocol: TCP
#       port: 443
#       targetPort: 443
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: homeassist-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   tls:
#     - hosts:
#         - homeassist.local
#       secretName: star-app-tls
#   rules:
#     - host: homeassist.local
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: homeassist
#                 port:
#                   number: 443