---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  chart:
    spec:
      chart: mongodb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  values:
    global:
      namespaceOverride: mongodb
    livenessProbe:
      initialDelaySeconds: 180
    auth:
      existingSecret: basic-auth
      username: user1
      password: user1
      database: mydb
    service:
      type: ClusterIP 

