apiVersion: v1
data:
    database: ENC[AES256_GCM,data:fpy057Z9WqI=,iv:71VF5neEWdH6QE2oZUPR3kGy0/YIqQHBUmG7FPIPEDM=,tag:wNwludHluuwhazRwKiyvOQ==,type:str]
    password: ENC[AES256_GCM,data:TsTFl0qRyKY=,iv:HzqxUtKnTDJqsxHNZ1L4lTIGes2HaspmG3IXNYcINLw=,tag:1BMreymDH1+CX0ogfbqrEg==,type:str]
    rootPassword: ENC[AES256_GCM,data:n3BefWPbYKI=,iv:xyoVEIUpMf/SIp4rkqjJDWW7kmoT6SWRJA4T+oYS0XQ=,tag:XV3RenVzVNe8x5Wn77eHPg==,type:str]
    username: ENC[AES256_GCM,data:zajPMH1wrH4=,iv:NN+LrSU0qtwg/grnl0mzLeLXfuK9DpkXf6Ro6i/VHko=,tag:gyn8QEgzgb5hbyO6fhNDsw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: basic-auth
    namespace: mongodb
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vxgckta3fudhphcjg7403u37n22tgklq0q59y7dkjg9lp9sqtyuqnk35e8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyV0FEdURvTG5lSVE5Rk0z
            Z1d4bUp3OTY1RXBuTERQY1dkYXhYd1VwRlUwCk1FMU1jeVJGcVJ5Tm1HWDNZRUlP
            MytyYzZHS1JiNFErQ1IwSE9KNnRtWFEKLS0tIEhxd1NiZ3gwK3dBUkdUT1RHZHhw
            czBFVFVRL2I0UFU5dXVOWmxsbGk1QlUK9MSLjGWwBVvmgcIc1edDKfVfjTriyMRJ
            sNqQdb3ILaSAhNzNrrjtwExUnI/0V9VSNwYfUhk6eH5kwqGWHADNUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-07T14:40:11Z"
    mac: ENC[AES256_GCM,data:6X4Da9VXfotpWaOaYaBdiq8pyRegBgAgcvx8fKC6Yue07wbqc+yjluCvoBFeE7Xw5BpROcgISXyolNEd++JIePK6npwSzCPzzuMGTJj/kQwZDsh+VQVETN6IOUqrPoogUk8VgJg07f7NnZPxFaotNdHMEkiQTH534Y2cn4s60sY=,iv:zZXuXRnQZW69vnLmry8iy/eC+w8TggIrfkbIqoOJ4ow=,tag:60lnfyedzDfoZ+ETD7cC9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
